"""Navigation logic generated by the Developer Agent.

The Developer Agent is required to define a single top-level function
``decide_next_move(state)`` that returns one of ``"FORWARD"``, ``"LEFT"``,
``"RIGHT"``, or ``"STOP"``. ``state`` is the sensor/goal snapshot the
simulator hands the robot. The exact keys inside ``state`` are not fixed by
the assignment; this default implementation matches the convention used in
the sample test fixture (goal direction + blocked flags) so the module is
importable and runnable even before Qwen has produced a real version.

The Developer Agent will overwrite this file when ``run_developer.py`` is
executed.
"""

from __future__ import annotations

from typing import Any


def decide_next_move(state: dict[str, Any]) -> str:
    """Return the next move for the robot given the current ``state``.

    The default implementation:
      * prefers moving toward the goal when that direction is clear,
      * otherwise picks any clear direction (forward preferred),
      * stops when every direction is blocked.
    """
    goal_ahead = bool(state.get("goal_ahead", False))
    goal_on_left = bool(state.get("goal_on_left", False))
    goal_on_right = bool(state.get("goal_on_right", False))
    front_blocked = bool(state.get("front_blocked", False))
    left_blocked = bool(state.get("left_blocked", False))
    right_blocked = bool(state.get("right_blocked", False))

    if goal_ahead and not front_blocked:
        return "FORWARD"
    if goal_on_left and not left_blocked:
        return "LEFT"
    if goal_on_right and not right_blocked:
        return "RIGHT"
    if not front_blocked:
        return "FORWARD"
    if not left_blocked:
        return "LEFT"
    if not right_blocked:
        return "RIGHT"
    return "STOP"